### ISSUE TITLE
Add an ignore option to inceptumApp.addDirectory method

### ISSUE THREAD

**Issue by pupudu** [hipages/inceptum#100]
Calling `addDirectory` on a new InceptumApp will add all files in the directory in a recursive manner. However, there can be instances where a user wants to ignore some files or subdirectories in a given path.

 For instance, if we write tests alongside the source files, with a `.test.js`/`.spec.js` prefix OR if we use a test directory as `__test__` /`test`, inceptum will try to add these files to the app. 

On the other hand, inceptum app will crash, if test specific configurations are there in the test files. (configs or globals which will be loaded by a test runner)

Thus there should be an options to Ignore sub-directories/files from the `addDirectory` method.

**Comment by pragone** [comment]
Interesting... why not just add the subdirectories you do want instead of adding the parent directory and ignoring some? Do you have a specific example document tree where this would be useful?

**Comment by pragone** [comment]
I've removed the "bug" label as I'm not clear what the expected behaviour should be based on the ticket

**Comment by pragone** [comment]
Sorry. closed by mistake
