### ISSUE TITLE
Define the API standard to use

### ISSUE THREAD

**Issue by pragone** [hipages/inceptum#9]
Should we use HAL? or is Swagger enough?
What autodiscovery capabilities do we want

**Comment by joeruello** [comment]
Alternative to HAL: [jsonapi](http://jsonapi.org/). Seems to be a little more opinionated about how to interact with resources on the server, whereas HAL is just more of a serialization format.

**Comment by pragone** [comment]
@estahn Care to share your thoughts here :)

**Comment by pragone** [comment]
@joeruello ... found jsonapi tremendously verbose. Not too clear on the opinionated piece... from what I saw it basically just described vanilla RESTful interactions. But perhaps didn't see deep enough.

**Comment by pragone** [comment]
Swagger has been chosen at this point. Now that we have a Plugin based architecture we could create plugins for other API standards. I'll close this for now. If there's any interest of implementing a different standard we should create a new ticket for it.
